#pragma once

enum EMessageType : uint8_t
{
    MESSAGE_TYPE_SC_CREATE_MY_CHARACTER = 0,
    MESSAGE_TYPE_SC_CREATE_OTHER_CHARACTER = 1,
    MESSAGE_TYPE_SC_DELETE_CHARACTER = 2,
    MESSAGE_TYPE_CS_MOVE = 10,
    MESSAGE_TYPE_SC_MOVE = 11,
    MESSAGE_TYPE_SC_CHAT = 21,
    MESSAGE_TYPE_CS_CHAT = 22,
    MESSAGE_TYPE_SC_PATH_FIND = 30,
    MESSAGE_TYPE_CS_HEARTBEAT = 100
};